//
// Created by Nicholas Kwon on 11/5/16.
//

#ifndef RICE_HDFS_UTIL_H
#define RICE_HDFS_UTIL_H
#include <boost/uuid/uuid.hpp>
#include <boost/uuid/uuid_generators.hpp>

namespace util {

    /**
     * Generates a random UUID using boost.
     * This method only uses the first 8 bytes of the UUID generated by boost.
     * @param uuid where to put the uuid.
     */
    inline void generate_uuid(std::uint64_t& uuid) {
        auto bytes = boost::uuids::random_generator()();
        memcpy((&uuid), &bytes, sizeof(std::uint64_t));
    }
}
#endif //RICE_HDFS_UTIL_H
