var searchData=
[
  ['rdfs_202_2e0',['RDFS 2.0',['../md__r_e_a_d_m_e.html',1,'']]],
  ['range_5fconst_5fiterator_3c_20pugi_3a_3axml_5fdocument_20_3e',['range_const_iterator&lt; pugi::xml_document &gt;',['../structboost_1_1range__const__iterator_3_01pugi_1_1xml__document_01_4.html',1,'boost']]],
  ['range_5fconst_5fiterator_3c_20pugi_3a_3axml_5fnode_20_3e',['range_const_iterator&lt; pugi::xml_node &gt;',['../structboost_1_1range__const__iterator_3_01pugi_1_1xml__node_01_4.html',1,'boost']]],
  ['range_5fmutable_5fiterator_3c_20pugi_3a_3axml_5fdocument_20_3e',['range_mutable_iterator&lt; pugi::xml_document &gt;',['../structboost_1_1range__mutable__iterator_3_01pugi_1_1xml__document_01_4.html',1,'boost']]],
  ['range_5fmutable_5fiterator_3c_20pugi_3a_3axml_5fnode_20_3e',['range_mutable_iterator&lt; pugi::xml_node &gt;',['../structboost_1_1range__mutable__iterator_3_01pugi_1_1xml__node_01_4.html',1,'boost']]],
  ['read_5ffile_5fznode',['read_file_znode',['../classzkclient_1_1_zk_nn_client.html#ac2b2d82a29053a95d0ed5573d67b6288',1,'zkclient::ZkNnClient']]],
  ['readopchecksuminfoproto',['ReadOpChecksumInfoProto',['../classhadoop_1_1hdfs_1_1_read_op_checksum_info_proto.html',1,'hadoop::hdfs']]],
  ['receiveddeletedblockinfoproto',['ReceivedDeletedBlockInfoProto',['../classhadoop_1_1hdfs_1_1datanode_1_1_received_deleted_block_info_proto.html',1,'hadoop::hdfs::datanode']]],
  ['reconfigure',['reconfigure',['../classel_1_1_logger.html#adfd57ab27fb398cc980a3edfab92927e',1,'el::Logger']]],
  ['reconfigureallloggers',['reconfigureAllLoggers',['../classel_1_1_loggers.html#a42f99e79d72d391df563df8d09272194',1,'el::Loggers::reconfigureAllLoggers(const Configurations &amp;configurations)'],['../classel_1_1_loggers.html#a1ebd33bc0208b430f41508e34509c7c9',1,'el::Loggers::reconfigureAllLoggers(ConfigurationType configurationType, const std::string &amp;value)'],['../classel_1_1_loggers.html#a396b601e204ede36f5a9acc76a8c5585',1,'el::Loggers::reconfigureAllLoggers(Level level, ConfigurationType configurationType, const std::string &amp;value)']]],
  ['reconfigurelogger',['reconfigureLogger',['../classel_1_1_loggers.html#a02223004494a404a2c3e7cd0c4380d3b',1,'el::Loggers::reconfigureLogger(Logger *logger, const Configurations &amp;configurations)'],['../classel_1_1_loggers.html#af3252cc39fa4ac17b4abf50acf6b4c5e',1,'el::Loggers::reconfigureLogger(const std::string &amp;identity, const Configurations &amp;configurations)'],['../classel_1_1_loggers.html#a89ec21259cfcfee3f761fca68c4ec043',1,'el::Loggers::reconfigureLogger(const std::string &amp;identity, ConfigurationType configurationType, const std::string &amp;value)']]],
  ['recoveringblockproto',['RecoveringBlockProto',['../classhadoop_1_1hdfs_1_1_recovering_block_proto.html',1,'hadoop::hdfs']]],
  ['recoverlease',['recoverLease',['../classclient__namenode__translator_1_1_client_namenode_translator.html#ab52cc5e09537eda6b2794eb9b4c2f604',1,'client_namenode_translator::ClientNamenodeTranslator']]],
  ['recoverleaserequestproto',['RecoverLeaseRequestProto',['../classhadoop_1_1hdfs_1_1_recover_lease_request_proto.html',1,'hadoop::hdfs']]],
  ['recoverleaseresponseproto',['RecoverLeaseResponseProto',['../classhadoop_1_1hdfs_1_1_recover_lease_response_proto.html',1,'hadoop::hdfs']]],
  ['recoveryspeed',['recoverySpeed',['../class_storage_metrics.html#a78f19e7a7079ccef8acc95a008636981',1,'StorageMetrics']]],
  ['recursive_5fcreate',['recursive_create',['../class_z_k_wrapper.html#a85c8c60cad7e38e945e6bcf603189d58',1,'ZKWrapper']]],
  ['recursive_5fdelete',['recursive_delete',['../class_z_k_wrapper.html#ad5bbbd3a3b26bf474127d124c0da33dc',1,'ZKWrapper']]],
  ['refreshcallqueuerequestproto',['RefreshCallQueueRequestProto',['../classhadoop_1_1common_1_1_refresh_call_queue_request_proto.html',1,'hadoop::common']]],
  ['refreshcallqueueresponseproto',['RefreshCallQueueResponseProto',['../classhadoop_1_1common_1_1_refresh_call_queue_response_proto.html',1,'hadoop::common']]],
  ['refreshnamenodesrequestproto',['RefreshNamenodesRequestProto',['../classhadoop_1_1hdfs_1_1_refresh_namenodes_request_proto.html',1,'hadoop::hdfs']]],
  ['refreshnamenodesresponseproto',['RefreshNamenodesResponseProto',['../classhadoop_1_1hdfs_1_1_refresh_namenodes_response_proto.html',1,'hadoop::hdfs']]],
  ['refreshnodesrequestproto',['RefreshNodesRequestProto',['../classhadoop_1_1hdfs_1_1_refresh_nodes_request_proto.html',1,'hadoop::hdfs']]],
  ['refreshnodesresponseproto',['RefreshNodesResponseProto',['../classhadoop_1_1hdfs_1_1_refresh_nodes_response_proto.html',1,'hadoop::hdfs']]],
  ['refreshserviceaclrequestproto',['RefreshServiceAclRequestProto',['../classhadoop_1_1common_1_1_refresh_service_acl_request_proto.html',1,'hadoop::common']]],
  ['refreshserviceaclresponseproto',['RefreshServiceAclResponseProto',['../classhadoop_1_1common_1_1_refresh_service_acl_response_proto.html',1,'hadoop::common']]],
  ['refreshsuperusergroupsconfigurationrequestproto',['RefreshSuperUserGroupsConfigurationRequestProto',['../classhadoop_1_1common_1_1_refresh_super_user_groups_configuration_request_proto.html',1,'hadoop::common']]],
  ['refreshsuperusergroupsconfigurationresponseproto',['RefreshSuperUserGroupsConfigurationResponseProto',['../classhadoop_1_1common_1_1_refresh_super_user_groups_configuration_response_proto.html',1,'hadoop::common']]],
  ['refreshusertogroupsmappingsrequestproto',['RefreshUserToGroupsMappingsRequestProto',['../classhadoop_1_1common_1_1_refresh_user_to_groups_mappings_request_proto.html',1,'hadoop::common']]],
  ['refreshusertogroupsmappingsresponseproto',['RefreshUserToGroupsMappingsResponseProto',['../classhadoop_1_1common_1_1_refresh_user_to_groups_mappings_response_proto.html',1,'hadoop::common']]],
  ['register_5fhandler',['register_handler',['../class_r_p_c_server.html#a0c5189383c36d165cf0bf4dd6512d432',1,'RPCServer']]],
  ['registercommandproto',['RegisterCommandProto',['../classhadoop_1_1hdfs_1_1datanode_1_1_register_command_proto.html',1,'hadoop::hdfs::datanode']]],
  ['registerdatanode',['registerDataNode',['../classzkclient_1_1_zk_client_dn.html#a28a9f13800cd420ad30f2c62ae25429f',1,'zkclient::ZkClientDn']]],
  ['registerdatanoderequestproto',['RegisterDatanodeRequestProto',['../classhadoop_1_1hdfs_1_1datanode_1_1_register_datanode_request_proto.html',1,'hadoop::hdfs::datanode']]],
  ['registerdatanoderesponseproto',['RegisterDatanodeResponseProto',['../classhadoop_1_1hdfs_1_1datanode_1_1_register_datanode_response_proto.html',1,'hadoop::hdfs::datanode']]],
  ['registeredhitcounters',['RegisteredHitCounters',['../classel_1_1base_1_1_registered_hit_counters.html',1,'el::base']]],
  ['registeredloggers',['RegisteredLoggers',['../classel_1_1base_1_1_registered_loggers.html',1,'el::base']]],
  ['registernew',['registerNew',['../classel_1_1base_1_1utils_1_1_registry.html#ab10b3dd25ff0df036e7a015635a15dee',1,'el::base::utils::Registry']]],
  ['registerrequestproto',['RegisterRequestProto',['../classhadoop_1_1hdfs_1_1namenode_1_1_register_request_proto.html',1,'hadoop::hdfs::namenode']]],
  ['registerresponseproto',['RegisterResponseProto',['../classhadoop_1_1hdfs_1_1namenode_1_1_register_response_proto.html',1,'hadoop::hdfs::namenode']]],
  ['registry',['Registry',['../classel_1_1base_1_1utils_1_1_registry.html#adf5e97aa801be3b93e116ad645304759',1,'el::base::utils::Registry']]],
  ['registry',['Registry',['../classel_1_1base_1_1utils_1_1_registry.html',1,'el::base::utils']]],
  ['registry_3c_20logger_2c_20std_3a_3astring_20_3e',['Registry&lt; Logger, std::string &gt;',['../classel_1_1base_1_1utils_1_1_registry.html',1,'el::base::utils']]],
  ['registrywithpred',['RegistryWithPred',['../classel_1_1base_1_1utils_1_1_registry_with_pred.html#a0e75c7daaa5fbf824b29180c7a5fd155',1,'el::base::utils::RegistryWithPred']]],
  ['registrywithpred',['RegistryWithPred',['../classel_1_1base_1_1utils_1_1_registry_with_pred.html',1,'el::base::utils']]],
  ['registrywithpred_3c_20base_3a_3ahitcounter_2c_20base_3a_3ahitcounter_3a_3apredicate_20_3e',['RegistryWithPred&lt; base::HitCounter, base::HitCounter::Predicate &gt;',['../classel_1_1base_1_1utils_1_1_registry_with_pred.html',1,'el::base::utils']]],
  ['registrywithpred_3c_20configuration_2c_20configuration_3a_3apredicate_20_3e',['RegistryWithPred&lt; Configuration, Configuration::Predicate &gt;',['../classel_1_1base_1_1utils_1_1_registry_with_pred.html',1,'el::base::utils']]],
  ['releasedate',['releaseDate',['../classel_1_1_version_info.html#a9347b5c0f386117f1cf78dae99bb1752',1,'el::VersionInfo']]],
  ['releaseshortcircuitaccessrequestproto',['ReleaseShortCircuitAccessRequestProto',['../classhadoop_1_1hdfs_1_1_release_short_circuit_access_request_proto.html',1,'hadoop::hdfs']]],
  ['releaseshortcircuitaccessresponseproto',['ReleaseShortCircuitAccessResponseProto',['../classhadoop_1_1hdfs_1_1_release_short_circuit_access_response_proto.html',1,'hadoop::hdfs']]],
  ['remoteeditlogmanifestproto',['RemoteEditLogManifestProto',['../classhadoop_1_1hdfs_1_1_remote_edit_log_manifest_proto.html',1,'hadoop::hdfs']]],
  ['remoteeditlogproto',['RemoteEditLogProto',['../classhadoop_1_1hdfs_1_1_remote_edit_log_proto.html',1,'hadoop::hdfs']]],
  ['removeaclentriesrequestproto',['RemoveAclEntriesRequestProto',['../classhadoop_1_1hdfs_1_1_remove_acl_entries_request_proto.html',1,'hadoop::hdfs']]],
  ['removeaclentriesresponseproto',['RemoveAclEntriesResponseProto',['../classhadoop_1_1hdfs_1_1_remove_acl_entries_response_proto.html',1,'hadoop::hdfs']]],
  ['removeaclrequestproto',['RemoveAclRequestProto',['../classhadoop_1_1hdfs_1_1_remove_acl_request_proto.html',1,'hadoop::hdfs']]],
  ['removeaclresponseproto',['RemoveAclResponseProto',['../classhadoop_1_1hdfs_1_1_remove_acl_response_proto.html',1,'hadoop::hdfs']]],
  ['removecachedirectiverequestproto',['RemoveCacheDirectiveRequestProto',['../classhadoop_1_1hdfs_1_1_remove_cache_directive_request_proto.html',1,'hadoop::hdfs']]],
  ['removecachedirectiveresponseproto',['RemoveCacheDirectiveResponseProto',['../classhadoop_1_1hdfs_1_1_remove_cache_directive_response_proto.html',1,'hadoop::hdfs']]],
  ['removecachepoolrequestproto',['RemoveCachePoolRequestProto',['../classhadoop_1_1hdfs_1_1_remove_cache_pool_request_proto.html',1,'hadoop::hdfs']]],
  ['removecachepoolresponseproto',['RemoveCachePoolResponseProto',['../classhadoop_1_1hdfs_1_1_remove_cache_pool_response_proto.html',1,'hadoop::hdfs']]],
  ['removedefaultaclrequestproto',['RemoveDefaultAclRequestProto',['../classhadoop_1_1hdfs_1_1_remove_default_acl_request_proto.html',1,'hadoop::hdfs']]],
  ['removedefaultaclresponseproto',['RemoveDefaultAclResponseProto',['../classhadoop_1_1hdfs_1_1_remove_default_acl_response_proto.html',1,'hadoop::hdfs']]],
  ['removeflag',['removeFlag',['../classel_1_1_loggers.html#a23fcb4b492f70a34285c45c0b5e2e515',1,'el::Loggers']]],
  ['removespanreceiverrequestproto',['RemoveSpanReceiverRequestProto',['../classhadoop_1_1common_1_1_remove_span_receiver_request_proto.html',1,'hadoop::common']]],
  ['removespanreceiverresponseproto',['RemoveSpanReceiverResponseProto',['../classhadoop_1_1common_1_1_remove_span_receiver_response_proto.html',1,'hadoop::common']]],
  ['removexattrrequestproto',['RemoveXAttrRequestProto',['../classhadoop_1_1hdfs_1_1_remove_x_attr_request_proto.html',1,'hadoop::hdfs']]],
  ['removexattrresponseproto',['RemoveXAttrResponseProto',['../classhadoop_1_1hdfs_1_1_remove_x_attr_response_proto.html',1,'hadoop::hdfs']]],
  ['rename',['rename',['../classzkclient_1_1_zk_nn_client.html#a6d4f66214cbadc6b06aabd8be2a8d382',1,'zkclient::ZkNnClient']]],
  ['rename2',['rename2',['../classclient__namenode__translator_1_1_client_namenode_translator.html#a6cb2eb48718ab49d5ec5b3e3520bd7ff',1,'client_namenode_translator::ClientNamenodeTranslator']]],
  ['rename2requestproto',['Rename2RequestProto',['../classhadoop_1_1hdfs_1_1_rename2_request_proto.html',1,'hadoop::hdfs']]],
  ['rename2responseproto',['Rename2ResponseProto',['../classhadoop_1_1hdfs_1_1_rename2_response_proto.html',1,'hadoop::hdfs']]],
  ['rename_5fops_5ffor_5ffile',['rename_ops_for_file',['../classzkclient_1_1_zk_nn_client.html#a88e442620389be579800e80523ccfcef',1,'zkclient::ZkNnClient']]],
  ['renameeventproto',['RenameEventProto',['../classhadoop_1_1hdfs_1_1_rename_event_proto.html',1,'hadoop::hdfs']]],
  ['renamerequestproto',['RenameRequestProto',['../classhadoop_1_1hdfs_1_1_rename_request_proto.html',1,'hadoop::hdfs']]],
  ['renameresponseproto',['RenameResponseProto',['../classhadoop_1_1hdfs_1_1_rename_response_proto.html',1,'hadoop::hdfs']]],
  ['renamesnapshotrequestproto',['RenameSnapshotRequestProto',['../classhadoop_1_1hdfs_1_1_rename_snapshot_request_proto.html',1,'hadoop::hdfs']]],
  ['renamesnapshotresponseproto',['RenameSnapshotResponseProto',['../classhadoop_1_1hdfs_1_1_rename_snapshot_response_proto.html',1,'hadoop::hdfs']]],
  ['renewdelegationtokenrequestproto',['RenewDelegationTokenRequestProto',['../classhadoop_1_1common_1_1_renew_delegation_token_request_proto.html',1,'hadoop::common']]],
  ['renewdelegationtokenresponseproto',['RenewDelegationTokenResponseProto',['../classhadoop_1_1common_1_1_renew_delegation_token_response_proto.html',1,'hadoop::common']]],
  ['renewleaserequestproto',['RenewLeaseRequestProto',['../classhadoop_1_1hdfs_1_1_renew_lease_request_proto.html',1,'hadoop::hdfs']]],
  ['renewleaseresponseproto',['RenewLeaseResponseProto',['../classhadoop_1_1hdfs_1_1_renew_lease_response_proto.html',1,'hadoop::hdfs']]],
  ['replaceall',['replaceAll',['../classel_1_1base_1_1utils_1_1_str.html#ab24bb11d2b5eb8ede4296d70b510f726',1,'el::base::utils::Str::replaceAll(std::string &amp;str, char replaceWhat, char replaceWith)'],['../classel_1_1base_1_1utils_1_1_str.html#a5f424d54390059c0a6a6f81a74ee846b',1,'el::base::utils::Str::replaceAll(std::string &amp;str, const std::string &amp;replaceWhat, const std::string &amp;replaceWith)']]],
  ['replicate',['replicate',['../class_transfer_server.html#aa178c0a06b2c2f073dccef1ac34a6c10',1,'TransferServer']]],
  ['reportbadblocksrequestproto',['ReportBadBlocksRequestProto',['../classhadoop_1_1hdfs_1_1datanode_1_1_report_bad_blocks_request_proto.html',1,'hadoop::hdfs::datanode']]],
  ['reportbadblocksrequestproto',['ReportBadBlocksRequestProto',['../classhadoop_1_1hdfs_1_1_report_bad_blocks_request_proto.html',1,'hadoop::hdfs']]],
  ['reportbadblocksresponseproto',['ReportBadBlocksResponseProto',['../classhadoop_1_1hdfs_1_1_report_bad_blocks_response_proto.html',1,'hadoop::hdfs']]],
  ['reportbadblocksresponseproto',['ReportBadBlocksResponseProto',['../classhadoop_1_1hdfs_1_1datanode_1_1_report_bad_blocks_response_proto.html',1,'hadoop::hdfs::datanode']]],
  ['requestheaderproto',['RequestHeaderProto',['../classhadoop_1_1common_1_1_request_header_proto.html',1,'hadoop::common']]],
  ['requestinfoproto',['RequestInfoProto',['../classhadoop_1_1hdfs_1_1qjournal_1_1_request_info_proto.html',1,'hadoop::hdfs::qjournal']]],
  ['resetlocation',['resetLocation',['../classel_1_1base_1_1_hit_counter.html#a56f5a7450080d31b8d54c2be877b8597',1,'el::base::HitCounter']]],
  ['restorefailedstoragerequestproto',['RestoreFailedStorageRequestProto',['../classhadoop_1_1hdfs_1_1_restore_failed_storage_request_proto.html',1,'hadoop::hdfs']]],
  ['restorefailedstorageresponseproto',['RestoreFailedStorageResponseProto',['../classhadoop_1_1hdfs_1_1_restore_failed_storage_response_proto.html',1,'hadoop::hdfs']]],
  ['rmblock',['rmBlock',['../classnativefs_1_1_native_f_s.html#a91f4e9ad8f1545fb084b1732ff3ef32d',1,'nativefs::NativeFS']]],
  ['rolleditlogrequestproto',['RollEditLogRequestProto',['../classhadoop_1_1hdfs_1_1namenode_1_1_roll_edit_log_request_proto.html',1,'hadoop::hdfs::namenode']]],
  ['rolleditlogresponseproto',['RollEditLogResponseProto',['../classhadoop_1_1hdfs_1_1namenode_1_1_roll_edit_log_response_proto.html',1,'hadoop::hdfs::namenode']]],
  ['rolleditsrequestproto',['RollEditsRequestProto',['../classhadoop_1_1hdfs_1_1_roll_edits_request_proto.html',1,'hadoop::hdfs']]],
  ['rolleditsresponseproto',['RollEditsResponseProto',['../classhadoop_1_1hdfs_1_1_roll_edits_response_proto.html',1,'hadoop::hdfs']]],
  ['rollingupgradeinfoproto',['RollingUpgradeInfoProto',['../classhadoop_1_1hdfs_1_1_rolling_upgrade_info_proto.html',1,'hadoop::hdfs']]],
  ['rollingupgraderequestproto',['RollingUpgradeRequestProto',['../classhadoop_1_1hdfs_1_1_rolling_upgrade_request_proto.html',1,'hadoop::hdfs']]],
  ['rollingupgraderesponseproto',['RollingUpgradeResponseProto',['../classhadoop_1_1hdfs_1_1_rolling_upgrade_response_proto.html',1,'hadoop::hdfs']]],
  ['rollingupgradestatusproto',['RollingUpgradeStatusProto',['../classhadoop_1_1hdfs_1_1_rolling_upgrade_status_proto.html',1,'hadoop::hdfs']]],
  ['rpcrequestheaderproto',['RpcRequestHeaderProto',['../classhadoop_1_1common_1_1_rpc_request_header_proto.html',1,'hadoop::common']]],
  ['rpcresponseheaderproto',['RpcResponseHeaderProto',['../classhadoop_1_1common_1_1_rpc_response_header_proto.html',1,'hadoop::common']]],
  ['rpcsaslproto',['RpcSaslProto',['../classhadoop_1_1common_1_1_rpc_sasl_proto.html',1,'hadoop::common']]],
  ['rpcsaslproto_5fsaslauth',['RpcSaslProto_SaslAuth',['../classhadoop_1_1common_1_1_rpc_sasl_proto___sasl_auth.html',1,'hadoop::common']]],
  ['rpcserver',['RPCServer',['../class_r_p_c_server.html',1,'RPCServer'],['../class_r_p_c_server.html#a016f4d4302f5e1bb15ba2b8cc270d4b4',1,'RPCServer::RPCServer()']]],
  ['rpctraceinfoproto',['RPCTraceInfoProto',['../classhadoop_1_1common_1_1_r_p_c_trace_info_proto.html',1,'hadoop::common']]]
];
